FROM gcc:11

# General
RUN set -eux && \
  apt-get update && \
  apt-get install --yes --no-install-recommends python3 python3-pip

RUN mkdir -p /root/.conan2/profiles
ADD conan_profile.conf /root/.conan2/profiles/default

# Conan
RUN set -eux && \
  pip install "conan>=2.0.0"

CMD [ "/bin/bash" ]
